name: My First Workflow

# trigger
on:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+'

jobs:
  # name of your job
  my-first-job:
    # runner
    runs-on: ubuntu-latest
    permissions: write-all
    # steps in this job
    steps:
      # - name: Run Trivy vulnerability scanner in fs mode
        # uses: aquasecurity/trivy-action@master
        # with:
          # scan-type: 'repo'
          # ignore-unfixed: true
          # format: 'github'
          # github-pat: ${{secrets.GH_TOKEN}}
          # output: 'dependency-results.sbom.json'
          # severity: 'LOW'
      # - name: Upload trivy report as a Github artifact
        # uses: actions/upload-artifact@v4
        # with:
          # name: trivy-sbom-report
          # path: '${{ github.workspace }}/dependency-results.sbom.json'
          # retention-days: 2 # 90 is the default
      # - name: Download artifact
        # uses: actions/download-artifact@v4
        # with:
          # name: trivy-sbom-report
      # - name: echo the git branch
        # uses: mscoutermarsh/cowsays-action@master
        # with:
          # text: "I am on branch ${{github.workspace}}"
          # color: cyan
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                  "type": "plain_text",
                    "text": "New request",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Type:*\nPaid Time Off"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Created by:*\n<example.com|Fred Enriquez>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*When:*\nAug 10 - Aug 13"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "Approve"
                      },
                      "style": "primary",
                      "value": "click_me_123"
                    },
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "emoji": true,
                        "text": "Reject"
                      },
                        "style": "danger",
                        "value": "click_me_123"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.MYTUNNEL }}
