name: My First Workflow

# trigger
on:
  - push

jobs:
  # name of your job
  my-first-job:
    # runner
    runs-on: ubuntu-latest
    permissions: write-all
    # steps in this job
    steps:
      - name: Run Trivy vulnerability scanner in fs mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'repo'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'LOW'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
      - name: echo the git branch
        uses: mscoutermarsh/cowsays-action@master
        with:
          text: "I am on branch ${{github.ref_name}}"
          color: cyan
